name: nionswift
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ipykernel
  - scikit-learn
  - nionswift
  - pip
  # pip packages (installed into the same env)
  - pip:
    - nionswift-io
    - nionswift-tool
    - nionswift-usim
    - nionswift-instrumentation
    - nionswift-experimental
    - nionswift-eels-analysis
    - nionswift-video-capture
    # nionswift extensions
    # - nionui
    # - nionswift-elabftw-plugin
    # - nionswift-segmentation